### ISSUE TITLE
blank string values in an attribute in Map Attribute turns to NoneType when using update statement on List

### ISSUE THREAD

**Issue by johnssuh** [MyMusicTaste/InPynamoDB#12]
Trying to update a ListAttribute with a MapAttribute value. Some of the values in the MapAttribute have UnicodeAttribute with null=True, default="".
When initializing MapAttribute, the UnicodeAttributes mentioned above have string type "" in them, but when I try to add it to the ListAttribute through update, it raises the following error:

![screen shot 2018-02-01 at 2 10 30 pm](https://user-images.githubusercontent.com/35440061/35662112-b42b711e-0759-11e8-929d-ca85d68362e8.png)

I think the values degenerate between the process from calling the update function to the dispatch. Not sure if this is Inpynamodb problem or pynamodb problem

**Comment by sunghyun-lee** [comment]
using blank string on attribute is forbidden, since this is nosql, you can just leave empty attribute as empty.
