### ISSUE TITLE
UTC location aware DateTime

### ISSUE THREAD

**Issue by johnssuh** [MyMusicTaste/InPynamoDB#14]
Currently, when we save an object with a UTCDatetimeAttribute, if the tzinfo is not set, it is assumed that the timezone is UTC 00:00. However, this results in incorrect time data, since if I have the default equal to datetime.datetime.now, then it automatically assumes UTC 00:00 when the location may not necessarily be where UTC is 00:00. 

I see two solutions. 
One: a hard requirement to give the tzinfo as the parameter - this would break some of the existing code but it will put responsibility on individual developers to specify the tzinfo. 
Two: the UTCDatetimeAttribute figuring out the tzinfo of the current location instead of simply defaulting to 00:00. This would be a cleaner solution I believe.

**Comment by sunghyun-lee** [comment]
Solved with using `datetime.datetime.utcnow()`
