### ISSUE TITLE
Query using LastEvaluatedKey for GSI including the last evaluated key's item itself

### ISSUE THREAD

**Issue by johnssuh** [MyMusicTaste/InPynamoDB#19]
Situation:
I have a global secondary index with a hash key and range key. 
When I query the index using a certain hash key with a last evaluated key from a previous query,
I get the list of items that STARTS with the item of last evaluated key.
For example,
let the following list of items [a,b,c,d] be a hypothetical table that I have. 
When I do limit = 1, then I get a. 
When I do limit =1 and last_evaluated_key=last_evaluated_key of previous query(which is = to a as key), then I still get a.
When I do limit = 2, then I get [a,b].
When I do limit = 2 and last_evaluated_key=last_evaluated_key of previous query(which is = to b as key), then I get [b,c].

The issue does not occur on local secondary index. I am not sure about regular queries on the model itself.

**Comment by sunghyun-lee** [comment]
gonna fix it by using `exclusive_start_key`
